### ISSUE TITLE
Feature: Replace deprecated :set-output: steps in workflows

### ISSUE THREAD

**Issue by abirismyname** [abirismyname/create-discussion#38]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by shaunakv1** [comment]
Hi @abirismyname 
I think this issue is fixed in [@actions/core](https://github.com/actions/toolkit/tree/HEAD/packages/core) now. Dependabot also has a PR ready for you :). Can we merge and get a new release please? 

https://github.com/abirismyname/create-discussion/pull/44

Thanks for a awesome action by the way :)

**Comment by abirismyname** [comment]
Hi there! Sorry I've have been updating this action as well as I should have been, Just released v1.2.0 which supports node 20 and has all the recent dependabot updates.
