### ISSUE TITLE
Upgrade to NODE 16

### ISSUE THREAD

**Issue by Pierre-kfoury** [abirismyname/create-discussion#52]
Hello ! 

I have noticed this on my CI 

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/8025495/216632593-a362a671-91b4-4824-afdc-5a16d88db3f8.png">

Thanks a lot for this feature

**Comment by nvdaes** [comment]
Hello: Seems that this action should update to Node 20:

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20

Thanks.

**Comment by nvdaes** [comment]
Hello. Seems that this useful action is not being maintained regularly. Then I may create another action to create discussions giving credit to this repo. I'vecreated an action, published on GitHub Marketplace,to get the repo ID to be used in Graphql calls, and I don't plan to fork this repo since I have a JavaScript file to create discussions, and I may make the new action to get the category ID specifying its position.
Thanks for this work.

**Comment by abirismyname** [comment]
Hi there! Sorry I've have been updating this action as well as I should have been, Just released v1.2.0 which supports node 20 and has all the recent dependabot updates. @nvdaes if you've additional feature requests feel free to create more issues.

**Comment by nvdaes** [comment]
Thanks @abirismyname.
 Since I didn't know if this action would be maintained, I created a build-discussion action mentioning that it's inspired by this one. I didn't copy your code at all, but I mention this action in the [readme of build-discussion](https://github.com/nvdaes/build-discussion).
